using System.Runtime.InteropServices;
using System.Security.Cryptography.X509Certificates;

namespace Tessio.Verifier.Trust.Tests;

/// <summary>
/// A two-tier ISO 18013-5 mdoc PKI: an IACA root and the document signer it issued. Both
/// certificates are public, taken from the EUDIW Unfold playground.
///
/// The other x5c fixtures in this suite are generated by <c>CertificateRequest</c> and carry no
/// critical extended key usage. A document signer carries a critical 1.0.18013.5.1.2, which changes
/// how chain building behaves.
/// </summary>
public sealed class RealMdocPkiTests
{
    static X509Certificate2 Load(string name)
    {
        var der = File.ReadAllBytes(Path.Combine("Fixtures", name));
#if NET9_0_OR_GREATER
        return X509CertificateLoader.LoadCertificate(der);
#else
        return new X509Certificate2(der);
#endif
    }

    static readonly Func<X509Certificate2> Iaca = () => Load("mdoc-iaca.der");
    static readonly Func<X509Certificate2> DocumentSigner = () => Load("mdoc-document-signer.der");

    [Fact]
    public void The_fixtures_really_are_an_issuer_and_the_signer_it_issued()
    {
        using var iaca = Iaca();
        using var ds = DocumentSigner();

        // Guards the fixtures themselves: if either is replaced with an unrelated certificate the
        // trust test below would start passing or failing for reasons that have nothing to do with
        // the code under test.
        Assert.Equal(iaca.Subject, ds.Issuer);
        Assert.Contains("1.0.18013.5.1.2", ds.Extensions
            .OfType<X509EnhancedKeyUsageExtension>()
            .SelectMany(e => e.EnhancedKeyUsages.Cast<System.Security.Cryptography.Oid>())
            .Select(o => o.Value));
    }

    [Fact]
    public async Task A_real_document_signer_anchors_on_its_own_iaca()
    {
        // The platforms disagree about this certificate pair. Apple's Security framework does not
        // complete a chain whose leaf carries a critical extended key usage it does not recognise,
        // and the mdoc document-signer OID 1.0.18013.5.1.2 is one; OpenSSL verifies the same pair.
        // Both outcomes are asserted rather than skipping on macOS, so a change on either platform
        // fails a test instead of passing silently.
        using var iaca = Iaca();
        using var ds = DocumentSigner();
        var resolver = new StaticTrustListResolver(["irrelevant"], trustAnchors: [iaca]);

        var status = await resolver.ResolveAsync(ds.Subject, [new ReadOnlyMemory<byte>(ds.RawData)]);

        if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            Assert.False(status.Trusted, "macOS now completes this chain; drop the platform split.");
            Assert.Contains("PartialChain", status.Reason, StringComparison.Ordinal);
            return;
        }

        Assert.True(status.Trusted, status.Reason);
    }
}
