using System.Security.Cryptography;

namespace Tessio.Verifier.Core.Mdoc.Tests;

/// <summary>
/// Hpke against RFC 9180's published Appendix A.3.1 vectors. The vector fixes the ephemeral key,
/// so sealing is deterministic and must reproduce the RFC's bytes exactly; nothing asserted here
/// was generated by this codebase.
/// </summary>
public sealed class HpkeTests
{
    private static ECDiffieHellman VectorKey(byte[]? privateScalar, byte[] uncompressedPoint) =>
        ECDiffieHellman.Create(new ECParameters
        {
            Curve = ECCurve.NamedCurves.nistP256,
            D = privateScalar,
            Q = new ECPoint { X = uncompressedPoint[1..33], Y = uncompressedPoint[33..] },
        });

    [Fact]
    public void Seal_WithTheVectorEphemeralKey_ReproducesTheRfcEncAndCiphertext()
    {
        using var ephemeral = VectorKey(Rfc9180Vectors.SkEm, Rfc9180Vectors.PkEm);
        using var recipient = VectorKey(privateScalar: null, Rfc9180Vectors.PkRm);

        var (enc, ciphertext) = Hpke.Seal(
            ephemeral, recipient, Rfc9180Vectors.Info, Rfc9180Vectors.Aad, Rfc9180Vectors.Plaintext);

        Assert.Equal(Rfc9180Vectors.Enc, enc);
        Assert.Equal(Rfc9180Vectors.Ciphertext, ciphertext);
    }

    [Fact]
    public void Open_WithTheVectorRecipientKey_ReturnsTheRfcPlaintext()
    {
        using var recipient = VectorKey(Rfc9180Vectors.SkRm, Rfc9180Vectors.PkRm);

        var plaintext = Hpke.Open(
            recipient, Rfc9180Vectors.Enc, Rfc9180Vectors.Info, Rfc9180Vectors.Aad,
            Rfc9180Vectors.Ciphertext);

        Assert.Equal(Rfc9180Vectors.Plaintext, plaintext);
    }

    [Fact]
    public void SealThenOpen_WithAFreshEphemeralKey_RoundTrips()
    {
        // The vector tests pin the injected-key path; this pins the only other way Seal is called.
        using var ephemeral = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);
        using var recipient = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);

        var (enc, ciphertext) = Hpke.Seal(
            ephemeral, recipient, Rfc9180Vectors.Info, Rfc9180Vectors.Aad, Rfc9180Vectors.Plaintext);
        var plaintext = Hpke.Open(recipient, enc, Rfc9180Vectors.Info, Rfc9180Vectors.Aad, ciphertext);

        Assert.Equal(Rfc9180Vectors.Plaintext, plaintext);
    }

    [Fact]
    public void Open_WithATamperedCiphertext_Throws()
    {
        using var recipient = VectorKey(Rfc9180Vectors.SkRm, Rfc9180Vectors.PkRm);
        var tampered = Rfc9180Vectors.Ciphertext;
        tampered[0] ^= 0x01;

        Assert.Throws<AuthenticationTagMismatchException>(() => Hpke.Open(
            recipient, Rfc9180Vectors.Enc, Rfc9180Vectors.Info, Rfc9180Vectors.Aad, tampered));
    }

    [Fact]
    public void Open_WithADifferentInfo_FailsTheTagCheck()
    {
        // A wrong info derives different keys, so decryption fails outright at the tag check;
        // it can never return wrong bytes. Callers can rely on that when diagnosing a mismatch.
        using var recipient = VectorKey(Rfc9180Vectors.SkRm, Rfc9180Vectors.PkRm);

        Assert.Throws<AuthenticationTagMismatchException>(() => Hpke.Open(
            recipient, Rfc9180Vectors.Enc, [0x00], Rfc9180Vectors.Aad, Rfc9180Vectors.Ciphertext));
    }

    [Fact]
    public void Open_WithADifferentAad_FailsTheTagCheck()
    {
        using var recipient = VectorKey(Rfc9180Vectors.SkRm, Rfc9180Vectors.PkRm);

        Assert.Throws<AuthenticationTagMismatchException>(() => Hpke.Open(
            recipient, Rfc9180Vectors.Enc, Rfc9180Vectors.Info, [0x00], Rfc9180Vectors.Ciphertext));
    }

    [Fact]
    public void Open_WithAMalformedEncapsulatedKey_Throws()
    {
        using var recipient = VectorKey(Rfc9180Vectors.SkRm, Rfc9180Vectors.PkRm);
        var truncated = Rfc9180Vectors.Enc[..64];

        var e = Assert.Throws<CryptographicException>(() => Hpke.Open(
            recipient, truncated, Rfc9180Vectors.Info, Rfc9180Vectors.Aad, Rfc9180Vectors.Ciphertext));
        Assert.Contains("encapsulated key", e.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Open_WithAnOffCurvePoint_Throws()
    {
        // Right length, right prefix, but the point is not on P-256. Computing a key agreement on
        // an attacker-chosen off-curve point must never happen, and the rejection must read the
        // same on every OS, so this asserts the library's own exception rather than the
        // platform's: Windows CNG answers an off-curve point with PlatformNotSupportedException.
        using var recipient = VectorKey(Rfc9180Vectors.SkRm, Rfc9180Vectors.PkRm);
        var offCurve = Rfc9180Vectors.Enc;
        Array.Clear(offCurve, 33, 32);

        var e = Assert.Throws<CryptographicException>(() => Hpke.Open(
            recipient, offCurve, Rfc9180Vectors.Info, Rfc9180Vectors.Aad, Rfc9180Vectors.Ciphertext));
        Assert.Contains("not on P-256", e.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void Seal_WithAKeyNotOnP256_Throws()
    {
        using var ephemeral = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP384);
        using var recipient = ECDiffieHellman.Create(ECCurve.NamedCurves.nistP256);

        Assert.Throws<CryptographicException>(() => Hpke.Seal(
            ephemeral, recipient, Rfc9180Vectors.Info, Rfc9180Vectors.Aad, Rfc9180Vectors.Plaintext));
    }
}
