using System.Security.Cryptography.X509Certificates;
using Tessio.Verifier.Core;
using Tessio.Verifier.Trust;

namespace Tessio.Verifier.Core.Mdoc.Tests;

/// <summary>
/// Conformance against the ISO/IEC 18013-5 Annex D worked example: externally produced bytes the
/// implementation must agree with. Unlike the builder-based tests, nothing here was generated by
/// this codebase, so a shared misreading of the spec between our issuer and verifier cannot pass.
/// The example's device auth is a proximity deviceMac, which this verifier rejects by design; the
/// full-pipeline test asserts that is the ONLY failure.
/// </summary>
public sealed class Iso18013AnnexDConformanceTests
{
    private const string MdlDocType = "org.iso.18013.5.1.mDL";
    private const string MdlNamespace = "org.iso.18013.5.1";

    /// <summary>
    /// Inside the vector's MSO validity window (signed 2020-10-01, validUntil 2021-10-01).
    /// </summary>
    /// <remarks>
    /// TWO constraints now, not one. The trust resolver reads the Document Signer certificate's own
    /// window at this same clock, and that certificate runs 2020-10-01 to 2021-10-01 (read from the
    /// vector with openssl, not assumed). The two happen to coincide, so a single instant satisfies
    /// both; moving this clock means checking it against both.
    /// </remarks>
    private sealed class AnnexDClock : TimeProvider
    {
        public override DateTimeOffset GetUtcNow() => new(2021, 1, 1, 0, 0, 0, TimeSpan.Zero);
    }

    private static string DeviceResponseBase64Url() =>
        Microsoft.IdentityModel.Tokens.Base64UrlEncoder.Encode(Iso18013AnnexDVectors.DeviceResponse);

    private static X509Certificate2 DsCertificate() =>
#if NET9_0_OR_GREATER
        X509CertificateLoader.LoadCertificate(Iso18013AnnexDVectors.DsCertificate);
#else
        new(Iso18013AnnexDVectors.DsCertificate);
#endif

    [Fact]
    public void Parse_ReadsTheAnnexDDocument()
    {
        var response = DeviceResponseParser.Parse(DeviceResponseBase64Url());

        Assert.Equal("1.0", response.Version);
        Assert.Equal(0, response.Status);
        var document = Assert.Single(response.Documents);
        Assert.Equal(MdlDocType, document.DocType);
        Assert.NotNull(document.DeviceSigned);

        var items = document.NameSpaces[MdlNamespace];
        Assert.Equal(6, items.Count);
        Assert.Equal("Doe", items.Single(i => i.ElementIdentifier == "family_name").ElementValue);
        Assert.Equal("123456789", items.Single(i => i.ElementIdentifier == "document_number").ElementValue);
        Assert.Equal("2019-10-20", items.Single(i => i.ElementIdentifier == "issue_date").ElementValue);
        Assert.Equal("2024-10-20", items.Single(i => i.ElementIdentifier == "expiry_date").ElementValue);
        Assert.IsType<byte[]>(items.Single(i => i.ElementIdentifier == "portrait").ElementValue);
    }

    [Fact]
    public void ParseMso_ReadsTheAnnexDValidityAndAlgorithm()
    {
        var document = DeviceResponseParser.Parse(DeviceResponseBase64Url()).Documents[0];

        var mso = DeviceResponseParser.ParseMso(document.IssuerAuth);

        Assert.Equal("SHA-256", mso.DigestAlgorithm);
        Assert.Equal(MdlDocType, mso.DocType);
        Assert.Equal(2020, mso.ValidFrom.Year);
        Assert.Equal(2021, mso.ValidUntil.Year);
        Assert.NotEmpty(mso.DeviceKeyEncoded);
    }

    [Fact]
    public void Digests_OfThePublishedItems_MatchThePublishedMso()
    {
        // The interop assertion: our digest computation over the transported IssuerSignedItemBytes
        // must reproduce the digests ISO published inside the example's MSO.
        var document = DeviceResponseParser.Parse(DeviceResponseBase64Url()).Documents[0];
        var mso = DeviceResponseParser.ParseMso(document.IssuerAuth);

        Assert.Empty(DigestVerifier.Verify(document, mso));
    }

    [Fact]
    public void IssuerAuth_VerifiesAgainstThePublishedDsCertificate()
    {
        var document = DeviceResponseParser.Parse(DeviceResponseBase64Url()).Documents[0];

        var resolution = IssuerAuthVerifier.Verify(document.IssuerAuth);

        // The x5chain leaf must be byte-identical to the separately published DS certificate.
        Assert.Equal(Iso18013AnnexDVectors.DsCertificate, resolution.CertificateChain[0].ToArray());
    }

    [Fact]
    public async Task FullPipeline_PassesEverything_ExceptTheProximityDeviceMac()
    {
        using var dsCert = DsCertificate();
        // THE SAME CLOCK ON BOTH HALVES. The resolver reads a pinned certificate's own validity
        // window, and this vector's certificate expired years ago in wall-clock terms. Giving the
        // verifier a 2021 clock and leaving the resolver on the system one would judge one frozen
        // artifact at two different instants, and the trust half would reject what the signature half
        // had just accepted.
        var clock = new AnnexDClock();
        var verifier = new MdocVerifier(
            new StaticTrustListResolver(
                [dsCert.Subject], source: "iso-annex-d", trustAnchors: [dsCert], clock: clock),
            clock: clock);

        var result = await verifier.VerifyAsync(
            new PresentedCredential { Format = MdocVerifier.Format, RawValue = DeviceResponseBase64Url() },
            new MdocVerificationContext
            {
                ExpectedDocType = MdlDocType,
                // The example is a proximity presentation; transcript inputs are placeholders and
                // never used because the deviceMac branch rejects first.
                ClientId = "n/a",
                Nonce = "n/a",
                ResponseUri = "n/a",
            });

        // Issuer signature, trust, validity and every digest pass; deviceMac is the sole failure.
        Assert.False(result.IsValid);
        Assert.True(result.Issuer.Trusted);
        var error = Assert.Single(result.Errors);
        Assert.Equal(MdocErrorCodes.DeviceAuthInvalid, error.Code);
        Assert.Contains("deviceMac", error.Message, StringComparison.Ordinal);
    }
}
